#!/usr/bin/env bash

#################################################################
# help:begin  
#
# helpdoc
# =======
# A KISS CLI tool for managing GNU style help messages.
# Extracts and stores help messages from comments in sourcecode and prints them when asked.
#
# Repository: https://github.com/SomajitDey/helpdoc
#
# License / Authors / Bug Reports: See repository
#
# Version: 0.1.0
#
# Usage: helpdoc [options] <command>
#
# Options:
# -e <source> : Extract help message for <command> form <source> file. If <command> is absent, derives command from <source> basename by removing extension
# -d : Delete help-file for <command> from database
# -a : Show only ABOUT message from <command>
# -u : Show only USAGE message from <command>
# -v : Show VERSION information from the ABOUT message, if any. If <command> is absent, shows self version.
# -h : Help for helpdoc
#
# Help Message Documentation Syntax: https://github.com/somajitdey/helpdoc#syntax
#
# Examples: https://github.com/somajitdey/helpdoc#examples
#
# help:end
#################################################################

# helpfile installation paths: local and system wide
local_ipath="${HOME}/.helpdoc"; mkdir -p "${local_ipath}" 2>/dev/null
sys_ipath='/etc/helpdoc'; mkdir -p "${sys_ipath}" 2>/dev/null

# help message header/footer/prefix (case insensitive)
help_begin='HELP:BEGIN[[:blank:]]*$' # Header with possibly trailing spaces/tabs
help_end='HELP:END[[:blank:]]*$' # Footer with possibly trailing spaces/tabs
usage_begin='USAGE:' # Prefix possibly followed by non-blank characters

set -o pipefail

extract_comment_marker(){
  # Extract comment marker from sourcefile provided as arg.
  local source="${1}"
  grep -m1 -i "${help_begin}" "${source}" | sed "s/${help_begin}//i" | xargs
  # xargs to clear leading and trailing space/tabs
}

extract_comment_remove_comment_marker(){
  # Extract comment and remove comment marker from sourcefile provided as arg.
  local source="${1}" comment_marker="${2}"
  grep "^[[:blank:]]*${comment_marker}" "${source}" | \
    sed 's/^[[:blank:]]*//' | cut -c "$((${#comment_marker}+1))-" # sed clears leading space/tabs
}

extract_between_patterns(){
  # Extracts lines between given (case-insensitive) patterns (inclusive) from stdin. Allows leading spaces/tabs
  local pat1="${1}" pat2="${2}"
  sed -n "/^[[:blank:]]*${pat1}/I,/^[[:blank:]]*${pat2}/Ip"
}

check_syntax(){
  #Check help message syntax in sourcefile provided as arg.
  local source="${1}" comment_marker="${2}"
  [[ -n "${comment_marker}" ]] && \
  grep -m1 -i -q "^[[:blank:]]*${comment_marker}[[:blank:]]*${help_end}" "${source}" && \
  grep -m1 -i -q "^[[:blank:]]*${comment_marker}[[:blank:]]*${usage_begin}" "${source}" || \
    { echo "Problem with help message format in ${source}"; exit 1;}
} >&2

extract_help(){
  # Extract help message from sourcefile provided as arg.
  local source="${1}"
  local comment_marker="$(extract_comment_marker "${source}")"

  check_syntax "${source}" "${comment_marker}"

  extract_comment_remove_comment_marker "${source}" "${comment_marker}" | \
    extract_between_patterns "${help_begin}" "${help_end}"
}

mode=help
while getopts :e:dauvh opt; do
  case "${opt}" in
    e) source="${OPTARG}"
       [[ -f "${source}" ]] || { echo "Couldn't open ${source} for reading"; exit 1;}
       mode=extract ;;
    d) mode=delete ;;
    a) mode=about ;;
    u) mode=usage ;;
    v) mode=version ;;
    h) helpdoc helpdoc; exit ;;
    *) echo 'Provided option not supported. See usage: helpdoc -h.' >&2; exit 1 ;;
  esac
done

command="${!OPTIND}"
[[ -n "${command}" ]] || [[ "${mode}" == extract ]] || [[ "${mode}" == version ]] || \
  { echo 'Pass a command name as argument. See usage: helpdoc -h.' >&2; exit 1;}

extract(){
  # Extracts help message from given source and creates helpfile
  # Helpfile is installed in local path if system path is denied
  # If no command is explicitly provided, derive command from source file basename by removing the extension(s)
  [[ -n "${command}" ]] || command="$(echo ${source##*/} | cut -d '.' -f1)"
  local tmpfile="$(mktemp)"; trap "rm -f ${tmpfile}" EXIT
  extract_help "${source}" > "${tmpfile}" || exit 1
  (mv -f "${tmpfile}" "${sys_ipath}/${command}" && chmod a+r "${sys_ipath}/${command}" \
    || mv -f "${tmpfile}" "${local_ipath}/${command}") 2>/dev/null \
      && echo "Installed helpfile for command: ${command}"
}

delete(){
  # Deletes helpfile. Tries deletion from local path if system path is denied
  rm --interactive=never "${sys_ipath}/${command}" || rm -f "${local_ipath}/${command}"
} 2>/dev/null

show_help(){
  # Show help file content. Gives precedence to locally installed helpfile.
  cat "${local_ipath}/${command}" || cat "${sys_ipath}/${command}"
} 2>/dev/null

about(){
  # Shows about message only
   show_help | extract_between_patterns "${help_begin}" "${usage_begin}" | \
    head -n -1 | tail -n +2 # Getting rid of the header and footer
} 2>/dev/null

usage(){
  # Shows usage message only. If no help file is found tries `command -h|--help` directly.
    show_help | extract_between_patterns "${usage_begin}" "${help_end}" | head -n -1 || \
    ("${command}" -h || "${command}" --help)
} 2>/dev/null

help(){
  # Shows both about and usage messages
  about && echo ; usage
}

version(){
  # Show version information
  [[ -n "${command}" ]] || command='helpdoc'
  about | grep -i '^[[:blank:]]*Version:' | cut -d ':' -f 2-
}

$mode
